version: '3.8'

services:
  db:
    image: postgres:15
    container_name: ecommerce-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ecommerce
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - ecommerce_net

  pgadmin:
    image: dpage/pgadmin4
    container_name: ecommerce-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - ecommerce_net

volumes:
  pgdata:
    name: ecommerce_pgdata

networks:
  ecommerce_net:
